config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "auth",
    controllers: {
      omniauth_callbacks: "omniauth_callbacks"
    },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      registration: 'register',
    }

  root "home#index"

  get 'me' => 'user#index'
  get 'me/polls' => 'user#polls'
  get 'me/voteds' => 'user#voteds'
  delete 'me/deactive' => 'user#deactive_me'

  get 'admin' => 'admin#index'
  get 'admin/reporteds' => 'admin#reporteds'
  get 'admin/users' => 'admin#users'
  put 'admin/user/:id' => 'admin#activate_user'
  delete 'admin/user/:id' => 'admin#deactive_user'
  delete 'admin/poll/:id' => 'admin#remove_poll'

  get 'search' => 'home#search'

  post 'polls' => 'poll#create'
  get 'polls/:id' => 'poll#index'
  put 'polls/:id' => 'poll#edit'
  delete 'polls/:id' => 'poll#delete'
  post 'polls/:id/report' => 'poll#report'


  post 'options' => 'option#create'
  post 'options/multiple' => 'option#create_multiple'
  put 'options' => 'option#edit'
  delete 'options' => 'option#delete'
 

  #vote
  post 'vote' => 'vote#vote'
  #undo vote
  post 'unvote' => 'vote#unvote'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :polls, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum role: [:user, :admin]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :rememberable, :trackable, :validatable

  def self.find_for_google_oauth2(access_token, signed_in_resource = nil)
    data = access_token.info

    user = User.find_by(:provider => access_token.provider, :uid => access_token.uid)
    return user if user

    registered_user = User.find_by(:email => access_token.info.email)
    return registered_user if registered_user

    user = User.create(
      provider: access_token.provider,
      email: data["email"],
      uid: access_token.uid ,
      password: Devise.friendly_token[0,20],
    )
  end

  def self.find_for_database_authentication(warden_conditions)
    where(warden_conditions).where(is_active: true).first
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  skip_before_filter :verify_authenticity_token, except: :index

  def index
    @polls = {
      own_polls: UserHelper.last_own_polls(current_user),
      voted_polls: UserHelper.last_voted_polls(current_user)
    }
  end

  def polls
    page = param! :page, Integer, required: true

    render json: UserHelper.last_own_polls(current_user, page)
  end

  def voteds
    page = param! :page, Integer, required: true

    render json: UserHelper.last_voted_polls(current_user, page)
  end

  def deactive_me
  end
end

app/helpers/user_helper.rb
module UserHelper

  def self.last_own_polls current_user, page = 1, per = 10
    last_polls = current_user.polls.order('id desc').page(page).per(per)
    votes = Vote.where(poll_id: last_polls.map(&:id)).group(:poll_id).count
    last_polls.map do |p|
      poll = p.attributes
      poll['total_count'] = votes[p.id].to_i 
      poll
    end
  end

  def self.last_voted_polls current_user, page = 1, per = 10
    votes = current_user.votes
    last_polls = Poll.where(id: votes.map(&:poll_id)).order('id desc').page(page).per(per)
    votes = Vote.where(poll_id: last_polls.map(&:id)).group(:poll_id).count
    last_polls.map do |p|
      poll = p.attributes
      poll['total_count'] = votes[p.id] 
      poll
    end
  end
end

app/views/user/index.html.erb
<div ng-controller="UserCtrl" ng-init='init(<%= @polls.to_json %>)'>

  <button type="button" class="btn btn-success" ng-click="hide_create = !hide_create">می خوام نظرسنجی درست کنم!</button>

  <br>
  <!-- Contact Section -->
  <section id="contact" collapse="hide_create">
    <br>

    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">

          <div class="panel panel-default">
            <div class="panel-body">

              <center><label>ایجاد نظرسنجی</label></center>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">موضوع</span>
                <input placeholder="این یه موضوع است!" maxlength="150" type="text" ng-model="form.poll.title" class="form-control" required>
              </div>

              <br>
              <div class="input-group">
                <span class="input-group-addon">توضیحات</span>
                <textarea class="form-control" ng-model="form.poll.description" rows="3"></textarea>
              </div>

              <br>
              <div class="input-group">
                <span class="input-group-addon">تگ ها</span>
                <input placeholder="تگ۱ تگ۲ تگ۳" class="form-control" ng-model="form.poll.tags"></input>
              </div>

              <br>
              <div class="col-lg-8 col-lg-offset-2">
                <div class="input-group" ng-repeat="index in range(0, form.poll.options.length)">
                  <span class="input-group-addon">گزینه {{index + 1}}:</span>
                  <input maxlength="150" type="text" ng-model="form.poll.options[index]"class="form-control" required>
                </div>
              </div>

              <br>
            </div>
            <center>
            <div >
              <button class="btn btn-primary" ng-click="form.submit()">بفرست</button>
            </div>
          </center>
          <br>

          </div>
        </div>
      </div>
    </div>

  </section>

  <br>

  <tabset>
  <tab heading="نظرسنجی های خودم">

  <div>
    <nav>
      <ul class="pager">
        <li class="previous"><a ng-click="getOwnPolls(-1)"><span aria-hidden="true">&larr;</span> قدیمی تر</a></li>
        <li class="next"><a ng-click="getOwnPolls(1)">جدیدتر <span aria-hidden="true">&rarr;</span></a></li>
      </ul>
    </nav>

    <div class="panel panel-default">

      <!-- Table -->
      <table class="table">
        <thead>
          <th>شماره</th>
          <th>آرا کل</th>
          <th>موضوع</th>
          <th>تگ ها</th>
        </thead>
        <tbody >
        <tr ng-repeat="poll in own_polls">
          <td class="col-md-1"><a href="/polls/{{poll.id}}">{{poll.id}}</a></td>
          <td class="col-md-2">{{poll.total_count}}</td>
          <td class="col-md-7" >{{poll.title}}</td>
          <td class="col-md-4" >{{poll.tags.join(' ')}}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>  

  </tab>
  <tab heading="مشارکت کرده ها">
  <div>
    <nav>
      <ul class="pager">
        <li class="previous"><a ng-click="getVotedPolls(-1)"><span aria-hidden="true">&larr;</span> قدیمی تر</a></li>
        <li class="next"><a ng-click="getVotedPolls(1)">جدیدتر <span aria-hidden="true">&rarr;</span></a></li>
      </ul>
    </nav>

    <div class="panel panel-default">

      <table class="table">
        <thead>
          <th>شماره</th>
          <th>آرا کل</th>
          <th>موضوع</th>
          <th>تگ ها</th>
        </thead>
        <tbody >
        <tr ng-repeat="poll in voted_polls">
          <td class="col-md-1"><a href="/polls/{{poll.id}}">{{poll.id}}</a></td>
          <td class="col-md-2">{{poll.total_count}}</td>
          <td class="col-md-7" >{{poll.title}}</td>
          <td class="col-md-4" >{{poll.tags.join(' ')}}</td>
        </tr>
        </tbody>
      </table>

    </div>  
  </div>  
  </tab>

  </tabset>

  <script type="text/ng-template" id="myModalContent.html">
    <div class="modal-header">
      <h3 class="modal-title">نظر سنجی شما ثبت شد.</h3>
    </div>
    <div class="modal-body">
      <%= link_to "برای دسترسی به نظر سنجی بر روی لینک کلیک کنید.", "#{polls_path}/{{poll.id}}" %> 
    </div>

    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" type="button" ng-click="ok()"></button>
    </div>
  </script> 

</div>