config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "auth",
    controllers: {
      omniauth_callbacks: "omniauth_callbacks"
    },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      registration: 'register',
    }

  root "home#index"

  get 'me' => 'user#index'
  get 'me/polls' => 'user#polls'
  get 'me/voteds' => 'user#voteds'
  delete 'me/deactive' => 'user#deactive_me'

  get 'admin' => 'admin#index'
  get 'admin/reporteds' => 'admin#reporteds'
  get 'admin/users' => 'admin#users'
  put 'admin/user/:id' => 'admin#activate_user'
  delete 'admin/user/:id' => 'admin#deactive_user'
  delete 'admin/poll/:id' => 'admin#remove_poll'

  get 'search' => 'home#search'

  post 'polls' => 'poll#create'
  get 'polls/:id' => 'poll#index'
  put 'polls/:id' => 'poll#edit'
  delete 'polls/:id' => 'poll#delete'
  post 'polls/:id/report' => 'poll#report'


  post 'options' => 'option#create'
  post 'options/multiple' => 'option#create_multiple'
  put 'options' => 'option#edit'
  delete 'options' => 'option#delete'
 

  #vote
  post 'vote' => 'vote#vote'
  #undo vote
  post 'unvote' => 'vote#unvote'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>کافکاخ</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag controller_name, media: 'all' %>
    <script src="/js/angular.min.js"></script>
    <script src="/js/d3.min.js"></script>
    <script src="/js/nv.d3.min.js"></script>
    <script src="/js/angular-nvd3.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag controller_name %>

    <link href="/css/bootstrap-rtl.min.css" rel="stylesheet" type="text/css">
    <link href="/css/nv.d3.min.css" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                </button>
                <a class="navbar-brand" href="#page-top">کافکاخ</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a href="/">خانه</a>
                    </li>
                    <% if user_signed_in? %>
                    <li>
                        <a href="/me">صفحه من</a>
                    </li>

                    <% if current_user.admin? %>
                      <li>
                      <%= link_to('ادمین', admin_path)  %>
                      </li>
                    <% end %>

                    <li>
                    <%= link_to('خروج', destroy_user_session_path, :method => :delete) %>
                    </li>
                    <% else %>
                    <li>
                    <%= link_to('ثبت نام', new_user_registration_path)  %>
                    </li>
                    <li>
                    <%= link_to('ورود', new_user_session_path)  %>
                    </li>

                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>


    <!-- Header -->
    <header>
      <br>
      <br>
      <br>
    </header>


   <div class="container" ng-app="kafka" class="app">
     <%= yield %>
   </div>


   <br>
   <br>
   <br>
    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                      با کافکاخ نظر دوستان خود را در مورد هرچیزی که دوست دارید بپرسید.!!
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>

</html>